version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - database

  database:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database  # Set the hostname or service name of your MySQL container
      ADMINER_DEFAULT_USERNAME: ${MYSQL_USER}  # Set the username for your MySQL database
      ADMINER_DEFAULT_PASSWORD: ${MYSQL_PASSWORD}  # Set the password for your MySQL database
      ADMINER_DESIGN: pappu  # You can specify a theme if desired
    depends_on:
      - database